# Therapeutic Optimization — Colab Runner

This notebook is intentionally lightweight. All reusable logic lives in `src/therapeutic_optimization/`.

Pipeline: **T1 → UP1 → T2 → S1 → R1 → UB2 → R2**.

Before publishing, replace the placeholder GitHub URL below with the real repository URL.

In [4]:
PROTEIN_ID = "my_protein"
WT_SEQUENCE = """PTAPPYDSLLVFDYEGGSGSGSGASRLNFGDDIPSALRIAKKKRWNSIEERRIHQESELHSYLSRLIAAERERELEECQRNHEGDEDDSHVRAQQACIEAKHDKYMADMDELFSQVDEKRKKRDIPDYLCGKISFELMREPCITPSGITYDRKDIEEHLQRVGHFDPVTRSPLTQEQLIPNLAMKEVIDAFISENGWVEDY"""

## Hyperparameters

`single` changes one selected lysine at a time. `combinatorial` generates orders 1 through `MAX_COMBINATION_ORDER` using every replacement amino acid listed in `REPLACEMENT_AAS`.

In [3]:
UBI_THRESHOLD = 0.40

MUTATION_MODE = "combinatorial"            # "single" or "combinatorial"
REPLACEMENT_AAS = ("R",)            # e.g. ("A", "R", "Q")
MAX_COMBINATION_ORDER = 4
MAX_VARIANTS = 5000

# S1 structural-preservation heuristic gates
GLOBAL_CA_RMSD_MAX = 1.0
LOCAL_MEAN_CA_DISPLACEMENT_MAX = 1.5
MUTATION_CA_DISPLACEMENT_MAX = 2.0
CONTACT_CHANGE_FRACTION_MAX = 0.10
MIN_MEAN_PLDDT = 70.0

## Runtime, dependencies, imports

Use a **GPU runtime**. EUP uses ESM2-3B and this implementation intentionally fails rather than silently falling back to a very slow CPU path.

In [1]:
from pathlib import Path
import os, shutil, subprocess, sys

REPO_URL = "https://github.com/juliaevizza/therapeutic_optimization.git"
REPO_DIR = Path("/content/therapeutic_optimization")

if not REPO_DIR.exists():
    subprocess.run(["git", "clone", "--depth", "1", REPO_URL, str(REPO_DIR)], check=True)
os.chdir(REPO_DIR)
print("Repository ready:", REPO_DIR)

# Run this after REPO_URL is configured and the repository has been cloned.
if REPO_DIR.exists():
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", "-e", f"{REPO_DIR}[eup]"], check=True)

    if shutil.which("git-lfs") is None:
        subprocess.run(["apt-get", "-qq", "update"], check=True)
        subprocess.run(["apt-get", "-qq", "install", "-y", "git-lfs"], check=True)
    subprocess.run(["git", "lfs", "install"], check=True)

    if shutil.which("colabfold_batch") is None:
        print("colabfold_batch not found. Installing the current CUDA 12 ColabFold stack...")
        subprocess.run([
            sys.executable, "-m", "pip", "install", "-q",
            "colabfold[alphafold,openmm]", "jax[cuda12]", "openmm[cuda12]"
        ], check=True)

    subprocess.run([sys.executable, str(REPO_DIR / "scripts" / "check_environment.py")], check=False)

Repository ready: /content/therapeutic_optimization
colabfold_batch not found. Installing the current CUDA 12 ColabFold stack...

## Choose where run outputs live

Set `SAVE_TO_DRIVE = True` if you want the run to survive Colab shutdown. The package code still runs from GitHub; only `storage/` outputs go into this run directory.

In [2]:
SAVE_TO_DRIVE = True

if SAVE_TO_DRIVE:
    from google.colab import drive
    drive.mount("/content/drive")
    RUN_ROOT = Path("/content/drive/MyDrive/therapeutic_optimization_run")
else:
    RUN_ROOT = Path("/content/therapeutic_optimization_run")

RUN_ROOT.mkdir(parents=True, exist_ok=True)
print("Run root:", RUN_ROOT)

Mounted at /content/drive
Run root: /content/drive/MyDrive/therapeutic_optimization_run

## Build the workflow

In [5]:
import sys
if 'therapeutic_optimization' in sys.modules:
    del sys.modules['therapeutic_optimization']
if "/content/therapeutic_optimization/src" not in sys.path:
    sys.path.insert(0, "/content/therapeutic_optimization/src")

from therapeutic_optimization.config import (
    MutationConfig,
    PredictorConfig,
    StructuralThresholds,
    WorkflowConfig,
)
from therapeutic_optimization.workflow import OptimizationWorkflow
from pathlib import Path

config = WorkflowConfig(
    mutation=MutationConfig(
        threshold=UBI_THRESHOLD,
        mode=MUTATION_MODE,
        replacement_aas=REPLACEMENT_AAS,
        max_combination_order=MAX_COMBINATION_ORDER,
        max_variants=MAX_VARIANTS,
    ),
    ubiquitination=PredictorConfig(
        name="eup",
        threshold=UBI_THRESHOLD,
        eup_repo_dir=Path("/content/external/EUP"),
        model_cache_dir=Path("/content/huggingface"),
    ),
    structural_thresholds=StructuralThresholds(
        global_ca_rmsd_max=GLOBAL_CA_RMSD_MAX,
        local_mean_ca_displacement_max=LOCAL_MEAN_CA_DISPLACEMENT_MAX,
        mutation_ca_displacement_max=MUTATION_CA_DISPLACEMENT_MAX,
        contact_change_fraction_max=CONTACT_CHANGE_FRACTION_MAX,
        min_mean_plddt=MIN_MEAN_PLDDT,
    ),
)

workflow = OptimizationWorkflow(RUN_ROOT, config)

## T1: input → WT FASTA

In [6]:
t1 = workflow.T1(WT_SEQUENCE, PROTEIN_ID)
t1

{'protein_id': 'my_protein',
 'sequence_length': 201,
 'wt_fasta': '/content/drive/MyDrive/therapeutic_optimization_run/storage/inputs/wt_input.fasta',
 'created_at_utc': '2026-09-01T18:57:23.195042+00:00'}

## UP1: WT ubiquitination prediction

In [7]:
up1 = workflow.UP1()
display(up1)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/779 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/95.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/93.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

pytorch_model.bin.index.json:   0%|          | 0.00/55.5k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

model.safetensors.index.json:   0%|          | 0.00/58.0k [00:00<?, ?B/s]

Loading weights:   0%|          | 0/582 [00:00<?, ?it/s]

[transformers] EsmModel LOAD REPORT from: facebook/esm2_t36_3B_UR50D
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.bias        | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.decoder.weight    | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
pooler.dense.weight       | MISSING    |
pooler.dense.bias         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

,variant_id,protein_id,predictor,lysine_position,site,sequence_context,probability,threshold,is_positive
0,WT,my_protein,EUP,153,K153,ITPSGITYDRKDIEEHLQRVG,0.609378,0.4,True
1,WT,my_protein,EUP,119,K119,MDELFSQVDEKRKKRDIPDYL,0.547615,0.4,True
2,WT,my_protein,EUP,185,K185,QEQLIPNLAMKEVIDAFISEN,0.524864,0.4,True
3,WT,my_protein,EUP,101,K101,VRAQQACIEAKHDKYMADMDE,0.499223,0.4,True
4,WT,my_protein,EUP,104,K104,QQACIEAKHDKYMADMDELFS,0.460844,0.4,True
5,WT,my_protein,EUP,132,K132,KRDIPDYLCGKISFELMREPC,0.400665,0.4,True
6,WT,my_protein,EUP,122,K122,LFSQVDEKRKKRDIPDYLCGK,0.332685,0.4,False
7,WT,my_protein,EUP,43,K43,IPSALRIAKKKRWNSIEERRI,0.302615,0.4,False
8,WT,my_protein,EUP,41,K41,DDIPSALRIAKKKRWNSIEER,0.288181,0.4,False
9,WT,my_protein,EUP,42,K42,DIPSALRIAKKKRWNSIEERR,0.245417,0.4,False
10,WT,my_protein,EUP,121,K121,ELFSQVDEKRKKRDIPDYLCG,0.176179,0.4,False

## T2: generate mutant FASTAs

In [8]:
t2 = workflow.T2(up1)
print(f"Generated {len(t2)} mutant(s).")
display(t2)

Generated 56 mutant(s).

,variant_id,mutation_spec,mutation_count,source_sites,replacement_aas,sequence_length,fasta_path,status,error
0,K101R,K101R,1,K101,R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
1,K104R,K104R,1,K104,R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
2,K119R,K119R,1,K119,R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
3,K132R,K132R,1,K132,R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
4,K153R,K153R,1,K153,R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
5,K185R,K185R,1,K185,R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
6,K101R__K104R,K101R;K104R,2,K101;K104,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
7,K101R__K119R,K101R;K119R,2,K101;K119,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
8,K101R__K132R,K101R;K132R,2,K101;K132,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
9,K101R__K153R,K101R;K153R,2,K101;K153,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
10,K101R__K185R,K101R;K185R,2,K101;K185,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
11,K104R__K119R,K104R;K119R,2,K104;K119,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
12,K104R__K132R,K104R;K132R,2,K104;K132,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
13,K104R__K153R,K104R;K153R,2,K104;K153,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
14,K104R__K185R,K104R;K185R,2,K104;K185,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
15,K119R__K132R,K119R;K132R,2,K119;K132,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
16,K119R__K153R,K119R;K153R,2,K119;K153,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
17,K119R__K185R,K119R;K185R,2,K119;K185,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
18,K132R__K153R,K132R;K153R,2,K132;K153,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
19,K132R__K185R,K132R;K185R,2,K132;K185,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
20,K153R__K185R,K153R;K185R,2,K153;K185,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
21,K101R__K104R__K119R,K101R;K104R;K119R,3,K101;K104;K119,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
22,K101R__K104R__K132R,K101R;K104R;K132R,3,K101;K104;K132,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
23,K101R__K104R__K153R,K101R;K104R;K153R,3,K101;K104;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
24,K101R__K104R__K185R,K101R;K104R;K185R,3,K101;K104;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
25,K101R__K119R__K132R,K101R;K119R;K132R,3,K101;K119;K132,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
26,K101R__K119R__K153R,K101R;K119R;K153R,3,K101;K119;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
27,K101R__K119R__K185R,K101R;K119R;K185R,3,K101;K119;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
28,K101R__K132R__K153R,K101R;K132R;K153R,3,K101;K132;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
29,K101R__K132R__K185R,K101R;K132R;K185R,3,K101;K132;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
30,K101R__K153R__K185R,K101R;K153R;K185R,3,K101;K153;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
31,K104R__K119R__K132R,K104R;K119R;K132R,3,K104;K119;K132,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
32,K104R__K119R__K153R,K104R;K119R;K153R,3,K104;K119;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
33,K104R__K119R__K185R,K104R;K119R;K185R,3,K104;K119;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
34,K104R__K132R__K153R,K104R;K132R;K153R,3,K104;K132;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
35,K104R__K132R__K185R,K104R;K132R;K185R,3,K104;K132;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
36,K104R__K153R__K185R,K104R;K153R;K185R,3,K104;K153;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
37,K119R__K132R__K153R,K119R;K132R;K153R,3,K119;K132;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
38,K119R__K132R__K185R,K119R;K132R;K185R,3,K119;K132;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
39,K119R__K153R__K185R,K119R;K153R;K185R,3,K119;K153;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
40,K132R__K153R__K185R,K132R;K153R;K185R,3,K132;K153;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
41,K101R__K104R__K119R__K132R,K101R;K104R;K119R;K132R,4,K101;K104;K119;K132,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
42,K101R__K104R__K119R__K153R,K101R;K104R;K119R;K153R,4,K101;K104;K119;K153,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
43,K101R__K104R__K119R__K185R,K101R;K104R;K119R;K185R,4,K101;K104;K119;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
44,K101R__K104R__K132R__K153R,K101R;K104R;K132R;K153R,4,K101;K104;K132;K153,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
45,K101R__K104R__K132R__K185R,K101R;K104R;K132R;K185R,4,K101;K104;K132;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
46,K101R__K104R__K153R__K185R,K101R;K104R;K153R;K185R,4,K101;K104;K153;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
47,K101R__K119R__K132R__K153R,K101R;K119R;K132R;K153R,4,K101;K119;K132;K153,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
48,K101R__K119R__K132R__K185R,K101R;K119R;K132R;K185R,4,K101;K119;K132;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
49,K101R__K119R__K153R__K185R,K101R;K119R;K153R;K185R,4,K101;K119;K153;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
50,K101R__K132R__K153R__K185R,K101R;K132R;K153R;K185R,4,K101;K132;K153;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
51,K104R__K119R__K132R__K153R,K104R;K119R;K132R;K153R,4,K104;K119;K132;K153,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
52,K104R__K119R__K132R__K185R,K104R;K119R;K132R;K185R,4,K104;K119;K132;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
53,K104R__K119R__K153R__K185R,K104R;K119R;K153R;K185R,4,K104;K119;K153;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
54,K104R__K132R__K153R__K185R,K104R;K132R;K153R;K185R,4,K104;K132;K153;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
55,K119R__K132R__K153R__K185R,K119R;K132R;K153R;K185R,4,K119;K132;K153;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None

## S1: structure prediction + preservation screen

This is the expensive structure stage. Every T2 mutant is predicted and compared with WT.

In [9]:
s1_metrics, s1_conserved = workflow.S1(t2, predict_structures=True)
print(f"Structurally conserved: {len(s1_conserved)} / {len(s1_metrics)}")
display(s1_metrics)
display(s1_conserved)

Structurally conserved: 15 / 56

,variant_id,mutation_spec,mutation_count,source_sites,replacement_aas,sequence_length,fasta_path,status,error,global_ca_rmsd,...,mean_centroid_distance_change,mean_residue_volume_change,per_residue_csv,displacement_plot,wt_structure,mutant_structure,analysis_status,analysis_error,structure_pass,structural_preservation_score
0,K101R,K101R,1,K101,R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.198691,...,0.184456,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.804786
1,K104R,K104R,1,K104,R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.026461,...,0.155044,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.776419
2,K119R,K119R,1,K119,R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.665016,...,-0.000419,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.853535
3,K132R,K132R,1,K132,R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.231865,...,-0.093565,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.773055
4,K153R,K153R,1,K153,R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,6.893741,...,0.488166,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.594300
5,K185R,K185R,1,K185,R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.643293,...,-0.061900,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.655991
6,K101R__K104R,K101R;K104R,2,K101;K104,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.215678,...,0.334055,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.775660
7,K101R__K119R,K101R;K119R,2,K101;K119,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.018296,...,0.062770,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.799149
8,K101R__K132R,K101R;K132R,2,K101;K132,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.786532,...,0.133368,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.840894
9,K101R__K153R,K101R;K153R,2,K101;K153,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.355376,...,0.150613,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.768647
10,K101R__K185R,K101R;K185R,2,K101;K185,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,2.230414,...,0.176114,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.677556
11,K104R__K119R,K104R;K119R,2,K104;K119,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.284641,...,0.305306,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.759956
12,K104R__K132R,K104R;K132R,2,K104;K132,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.859989,...,0.173677,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.814307
13,K104R__K153R,K104R;K153R,2,K104;K153,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.873506,...,0.068264,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.816032
14,K104R__K185R,K104R;K185R,2,K104;K185,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,7.073160,...,0.106728,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.589321
15,K119R__K132R,K119R;K132R,2,K119;K132,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,7.006277,...,-0.263550,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.553257
16,K119R__K153R,K119R;K153R,2,K119;K153,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.375230,...,0.140531,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.735175
17,K119R__K185R,K119R;K185R,2,K119;K185,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.204333,...,-0.099756,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.738933
18,K132R__K153R,K132R;K153R,2,K132;K153,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.608238,...,0.085272,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.861633
19,K132R__K185R,K132R;K185R,2,K132;K185,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.164629,...,-0.236853,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.758493
20,K153R__K185R,K153R;K185R,2,K153;K185,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.393736,...,-0.073041,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.745900
21,K101R__K104R__K119R,K101R;K104R;K119R,3,K101;K104;K119,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.680283,...,0.132067,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.847902
22,K101R__K104R__K132R,K101R;K104R;K132R,3,K101;K104;K132,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.396220,...,0.137470,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.748081
23,K101R__K104R__K153R,K101R;K104R;K153R,3,K101;K104;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.740591,...,0.127613,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.848609
24,K101R__K104R__K185R,K101R;K104R;K185R,3,K101;K104;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.818303,...,0.151946,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.817943
25,K101R__K119R__K132R,K101R;K119R;K132R,3,K101;K119;K132,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.763156,...,0.300420,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.675633
26,K101R__K119R__K153R,K101R;K119R;K153R,3,K101;K119;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.920941,...,0.100355,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.764117
27,K101R__K119R__K185R,K101R;K119R;K185R,3,K101;K119;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.185813,...,0.100447,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.759889
28,K101R__K132R__K153R,K101R;K132R;K153R,3,K101;K132;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,2.009559,...,0.130634,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.660095
29,K101R__K132R__K185R,K101R;K132R;K185R,3,K101;K132;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.489697,...,0.015252,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.671075
30,K101R__K153R__K185R,K101R;K153R;K185R,3,K101;K153;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.982769,...,0.015216,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.807731
31,K104R__K119R__K132R,K104R;K119R;K132R,3,K104;K119;K132,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.353768,...,0.036415,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.740520
32,K104R__K119R__K153R,K104R;K119R;K153R,3,K104;K119;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.195267,...,0.132041,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.746685
33,K104R__K119R__K185R,K104R;K119R;K185R,3,K104;K119;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.226369,...,0.020554,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.725151
34,K104R__K132R__K153R,K104R;K132R;K153R,3,K104;K132;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.513462,...,0.016180,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.725314
35,K104R__K132R__K185R,K104R;K132R;K185R,3,K104;K132;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.747513,...,-0.018730,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.653685
36,K104R__K153R__K185R,K104R;K153R;K185R,3,K104;K153;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.709365,...,-0.024580,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.840724
37,K119R__K132R__K153R,K119R;K132R;K153R,3,K119;K132;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.923188,...,0.088856,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.808558
38,K119R__K132R__K185R,K119R;K132R;K185R,3,K119;K132;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,6.845088,...,-0.194349,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.542012
39,K119R__K153R__K185R,K119R;K153R;K185R,3,K119;K153;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.063210,...,-0.114611,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.797044
40,K132R__K153R__K185R,K132R;K153R;K185R,3,K132;K153;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.032171,...,-0.143127,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.794416
41,K101R__K104R__K119R__K132R,K101R;K104R;K119R;K132R,4,K101;K104;K119;K132,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.891877,...,0.151966,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.791752
42,K101R__K104R__K119R__K153R,K101R;K104R;K119R;K153R,4,K101;K104;K119;K153,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.256386,...,0.117008,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.740986
43,K101R__K104R__K119R__K185R,K101R;K104R;K119R;K185R,4,K101;K104;K119;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.039629,...,0.175988,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.795489
44,K101R__K104R__K132R__K153R,K101R;K104R;K132R;K153R,4,K101;K104;K132;K153,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.197186,...,0.182552,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.774573
45,K101R__K104R__K132R__K185R,K101R;K104R;K132R;K185R,4,K101;K104;K132;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.323631,...,0.158637,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.761055
46,K101R__K104R__K153R__K185R,K101R;K104R;K153R;K185R,4,K101;K104;K153;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.110739,...,0.117347,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.740498
47,K101R__K119R__K132R__K153R,K101R;K119R;K132R;K153R,4,K101;K119;K132;K153,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.317164,...,0.179115,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.738133
48,K101R__K119R__K132R__K185R,K101R;K119R;K132R;K185R,4,K101;K119;K132;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,6.747614,...,-0.019968,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.535298
49,K101R__K119R__K153R__K185R,K101R;K119R;K153R;K185R,4,K101;K119;K153;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.918753,...,0.357094,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.777788
50,K101R__K132R__K153R__K185R,K101R;K132R;K153R;K185R,4,K101;K132;K153;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.774483,...,0.062010,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.833718
51,K104R__K119R__K132R__K153R,K104R;K119R;K132R;K153R,4,K104;K119;K132;K153,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.326047,...,0.014298,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.779653

,variant_id,mutation_spec,mutation_count,source_sites,replacement_aas,sequence_length,fasta_path,status,error,global_ca_rmsd,...,mean_centroid_distance_change,mean_residue_volume_change,per_residue_csv,displacement_plot,wt_structure,mutant_structure,analysis_status,analysis_error,structure_pass,structural_preservation_score
18,K132R__K153R,K132R;K153R,2,K132;K153,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.608238,...,0.085272,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.861633
2,K119R,K119R,1,K119,R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.665016,...,-0.000419,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.853535
23,K101R__K104R__K153R,K101R;K104R;K153R,3,K101;K104;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.740591,...,0.127613,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.848609
21,K101R__K104R__K119R,K101R;K104R;K119R,3,K101;K104;K119,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.680283,...,0.132067,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.847902
8,K101R__K132R,K101R;K132R,2,K101;K132,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.786532,...,0.133368,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.840894
36,K104R__K153R__K185R,K104R;K153R;K185R,3,K104;K153;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.709365,...,-0.024580,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.840724
50,K101R__K132R__K153R__K185R,K101R;K132R;K153R;K185R,4,K101;K132;K153;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.774483,...,0.062010,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.833718
24,K101R__K104R__K185R,K101R;K104R;K185R,3,K101;K104;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.818303,...,0.151946,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.817943
13,K104R__K153R,K104R;K153R,2,K104;K153,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.873506,...,0.068264,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.816032
12,K104R__K132R,K104R;K132R,2,K104;K132,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.859989,...,0.173677,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.814307
37,K119R__K132R__K153R,K119R;K132R;K153R,3,K119;K132;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.923188,...,0.088856,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.808558
30,K101R__K153R__K185R,K101R;K153R;K185R,3,K101;K153;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.982769,...,0.015216,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.807731
41,K101R__K104R__K119R__K132R,K101R;K104R;K119R;K132R,4,K101;K104;K119;K132,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.891877,...,0.151966,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.791752
49,K101R__K119R__K153R__K185R,K101R;K119R;K153R;K185R,4,K101;K119;K153;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.918753,...,0.357094,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.777788
26,K101R__K119R__K153R,K101R;K119R;K153R,3,K101;K119;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.920941,...,0.100355,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.764117

## R1: record structural dropouts

In [10]:
r1 = workflow.R1(t2, s1_metrics)
display(r1)

,variant_id,mutation_spec,mutation_count,source_sites,replacement_aas,sequence_length,fasta_path,status,error,analysis_status,analysis_error,structure_pass,structural_preservation_score,global_ca_rmsd,local_mean_ca_displacement,mutation_ca_displacement_max,global_contact_change_fraction,mutant_mean_plddt,dropped_after_S1,R1_status
0,K132R__K153R,K132R;K153R,2,K132;K153,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,True,0.861633,0.608238,0.277227,0.330460,0.007663,82.561990,False,ADVANCE_TO_UB2
1,K119R,K119R,1,K119,R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,True,0.853535,0.665016,0.302843,0.426344,0.003836,82.689950,False,ADVANCE_TO_UB2
2,K101R__K104R__K153R,K101R;K104R;K153R,3,K101;K104;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,True,0.848609,0.740591,0.238881,0.405581,0.006394,82.633184,False,ADVANCE_TO_UB2
3,K101R__K104R__K119R,K101R;K104R;K119R,3,K101;K104;K119,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,True,0.847902,0.680283,0.345890,0.460689,0.003841,82.932786,False,ADVANCE_TO_UB2
4,K101R__K132R,K101R;K132R,2,K101;K132,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,True,0.840894,0.786532,0.318174,0.431226,0.003836,83.077960,False,ADVANCE_TO_UB2
5,K104R__K153R__K185R,K104R;K153R;K185R,3,K104;K153;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,True,0.840724,0.709365,0.342511,0.532133,0.003841,82.471095,False,ADVANCE_TO_UB2
6,K101R__K132R__K153R__K185R,K101R;K132R;K153R;K185R,4,K101;K132;K153;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,True,0.833718,0.774483,0.347032,0.467450,0.007673,82.673682,False,ADVANCE_TO_UB2
7,K101R__K104R__K185R,K101R;K104R;K185R,3,K101;K104;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,True,0.817943,0.818303,0.446159,0.585775,0.007663,83.234577,False,ADVANCE_TO_UB2
8,K104R__K153R,K104R;K153R,2,K104;K153,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,True,0.816032,0.873506,0.427608,0.572385,0.005128,82.818856,False,ADVANCE_TO_UB2
9,K104R__K132R,K104R;K132R,2,K104;K132,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,True,0.814307,0.859989,0.386375,0.645338,0.006402,82.366617,False,ADVANCE_TO_UB2
10,K119R__K132R__K153R,K119R;K132R;K153R,3,K119;K132;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,True,0.808558,0.923188,0.358848,0.734654,0.002564,82.048209,False,ADVANCE_TO_UB2
11,K101R__K153R__K185R,K101R;K153R;K185R,3,K101;K153;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,True,0.807731,0.982769,0.392154,0.467806,0.008940,82.240697,False,ADVANCE_TO_UB2
12,K101R__K104R__K119R__K132R,K101R;K104R;K119R;K132R,4,K101;K104;K119;K132,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,True,0.791752,0.891877,0.501635,0.857182,0.007663,82.451891,False,ADVANCE_TO_UB2
13,K101R__K119R__K153R__K185R,K101R;K119R;K153R;K185R,4,K101;K119;K153;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,True,0.777788,0.918753,0.512369,1.029889,0.008963,82.139403,False,ADVANCE_TO_UB2
14,K101R__K119R__K153R,K101R;K119R;K153R,3,K101;K119;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,True,0.764117,0.920941,0.599349,1.207743,0.007653,82.104129,False,ADVANCE_TO_UB2
15,K101R,K101R,1,K101,R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.804786,1.198691,0.230488,0.299185,0.010178,82.579204,True,DROPPED_STRUCTURAL
16,K101R__K119R,K101R;K119R,2,K101;K119,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.799149,1.018296,0.435020,0.564604,0.007682,82.946468,True,DROPPED_STRUCTURAL
17,K119R__K153R__K185R,K119R;K153R;K185R,3,K119;K153;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.797044,1.063210,0.346787,0.630693,0.007663,82.840995,True,DROPPED_STRUCTURAL
18,K119R__K132R__K153R__K185R,K119R;K132R;K153R;K185R,4,K119;K132;K153;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.796085,1.083253,0.413346,0.590149,0.005122,83.298060,True,DROPPED_STRUCTURAL
19,K101R__K104R__K119R__K185R,K101R;K104R;K119R;K185R,4,K101;K104;K119;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.795489,1.039629,0.384781,0.553294,0.011465,82.116716,True,DROPPED_STRUCTURAL
20,K132R__K153R__K185R,K132R;K153R;K185R,3,K132;K153;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.794416,1.032171,0.442592,0.580356,0.007653,81.904826,True,DROPPED_STRUCTURAL
21,K104R__K119R__K132R__K153R,K104R;K119R;K132R;K153R,4,K104;K119;K132;K153,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.779653,1.326047,0.322815,0.426063,0.010191,82.636716,True,DROPPED_STRUCTURAL
22,K104R,K104R,1,K104,R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.776419,1.026461,0.616654,0.798726,0.005122,82.616617,True,DROPPED_STRUCTURAL
23,K101R__K104R,K101R;K104R,2,K101;K104,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.775660,1.215678,0.440033,0.515768,0.012723,82.537065,True,DROPPED_STRUCTURAL
24,K101R__K104R__K132R__K153R,K101R;K104R;K132R;K153R,4,K101;K104;K132;K153,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.774573,1.197186,0.358565,0.614027,0.015228,82.062786,True,DROPPED_STRUCTURAL
25,K132R,K132R,1,K132,R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.773055,1.231865,0.441414,0.489183,0.015228,82.678209,True,DROPPED_STRUCTURAL
26,K101R__K153R,K101R;K153R,2,K101;K153,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.768647,1.355376,0.320569,0.485628,0.015209,82.523085,True,DROPPED_STRUCTURAL
27,K104R__K132R__K153R__K185R,K104R;K132R;K153R;K185R,4,K104;K132;K153;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.764561,1.276477,0.463923,0.633147,0.011465,83.129851,True,DROPPED_STRUCTURAL
28,K101R__K104R__K132R__K185R,K101R;K104R;K132R;K185R,4,K101;K104;K132;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.761055,1.323631,0.429173,0.580917,0.013995,82.535124,True,DROPPED_STRUCTURAL
29,K104R__K119R,K104R;K119R,2,K104;K119,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.759956,1.284641,0.553150,0.687794,0.003841,81.763831,True,DROPPED_STRUCTURAL
30,K101R__K119R__K185R,K101R;K119R;K185R,3,K101;K119;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.759889,1.185813,0.506511,0.810543,0.011480,82.122189,True,DROPPED_STRUCTURAL
31,K132R__K185R,K132R;K185R,2,K132;K185,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.758493,1.164629,0.612218,0.793473,0.008917,82.180796,True,DROPPED_STRUCTURAL
32,K101R__K104R__K132R,K101R;K104R;K132R,3,K101;K104;K132,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.748081,1.396220,0.508168,0.706760,0.007643,82.281244,True,DROPPED_STRUCTURAL
33,K104R__K119R__K153R,K104R;K119R;K153R,3,K104;K119;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.746685,1.195267,0.671007,0.879441,0.008940,81.928557,True,DROPPED_STRUCTURAL
34,K153R__K185R,K153R;K185R,2,K153;K185,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.745900,1.393736,0.530109,0.537990,0.016477,81.995025,True,DROPPED_STRUCTURAL
35,K101R__K104R__K119R__K153R,K101R;K104R;K119R;K153R,4,K101;K104;K119;K153,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.740986,1.256386,0.673611,0.935984,0.005122,81.726418,True,DROPPED_STRUCTURAL
36,K104R__K119R__K132R,K104R;K119R;K132R,3,K104;K119;K132,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.740520,1.353768,0.514710,0.858001,0.010178,81.644527,True,DROPPED_STRUCTURAL
37,K101R__K104R__K153R__K185R,K101R;K104R;K153R;K185R,4,K101;K104;K153;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.740498,1.110739,0.759020,1.132394,0.006394,82.593284,True,DROPPED_STRUCTURAL
38,K119R__K185R,K119R;K185R,2,K119;K185,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.738933,1.204333,0.713086,0.963105,0.010217,82.638756,True,DROPPED_STRUCTURAL
39,K101R__K119R__K132R__K153R,K101R;K119R;K132R;K153R,4,K101;K119;K132;K153,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.738133,1.317164,0.598040,0.926442,0.008929,82.484925,True,DROPPED_STRUCTURAL
40,K119R__K153R,K119R;K153R,2,K119;K153,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.735175,1.375230,0.529416,0.832579,0.013977,81.799154,True,DROPPED_STRUCTURAL
41,K104R__K119R__K153R__K185R,K104R;K119R;K153R;K185R,4,K104;K119;K153;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.733053,1.312632,0.581001,0.902288,0.016497,82.330647,True,DROPPED_STRUCTURAL
42,K104R__K132R__K153R,K104R;K132R;K153R,3,K104;K132;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.725314,1.513462,0.474835,0.739817,0.018987,82.147164,True,DROPPED_STRUCTURAL
43,K104R__K119R__K185R,K104R;K119R;K185R,3,K104;K119;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.725151,1.226369,0.876161,1.089761,0.003846,82.266667,True,DROPPED_STRUCTURAL
44,K101R__K185R,K101R;K185R,2,K101;K185,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.677556,2.230414,0.565185,0.628867,0.016477,81.577363,True,DROPPED_STRUCTURAL
45,K101R__K119R__K132R,K101R;K119R;K132R,3,K101;K119;K132,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.675633,1.763156,0.656135,1.052615,0.015209,81.765622,True,DROPPED_STRUCTURAL
46,K101R__K132R__K185R,K101R;K132R;K185R,3,K101;K132;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.671075,1.489697,0.883650,1.289633,0.020228,81.831990,True,DROPPED_STRUCTURAL
47,K101R__K132R__K153R,K101R;K132R;K153R,3,K101;K132;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.660095,2.009559,0.627813,0.902935,0.017677,82.386169,True,DROPPED_STRUCTURAL
48,K185R,K185R,1,K185,R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.655991,1.643293,1.019991,0.999122,0.027604,82.939602,True,DROPPED_STRUCTURAL
49,K104R__K132R__K185R,K104R;K132R;K185R,3,K104;K132;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.653685,1.747513,0.861046,1.262346,0.016477,82.716368,True,DROPPED_STRUCTURAL
50,K153R,K153R,1,K153,R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.594300,6.893741,1.152172,1.190556,0.033624,82.131443,True,DROPPED_STRUCTURAL
51,K104R__K185R,K104R;K185R,2,K104;K185,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.589321,7.073160,1.216123,1.463290,0.021465,82.512736,True,DROPPED_STRUCTURAL
52,K119R__K132R,K119R;K132R,2,K119;K132,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.553257,7.006277,1.500628,1.816975,0.020177,82.161990,True,DROPPED_STRUCTURAL
53,K119R__K132R__K185R,K119R;K132R;K185R,3,K119;K132;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.542012,6.845088,1.600881,1.786245,0.026382,82.215821,True,DROPPED_STRUCTURAL
54,K104R__K119R__K132R__K185R,K104R;K119R;K132R;K185R,4,K104;K119;K132;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.538978,6.990388,1.495955,1.919330,0.028858,81.766318,True,DROPPED_STRUCTURAL
55,K101R__K119R__K132R__K185R,K101R;K119R;K132R;K185R,4,K101;K119;K132;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.535298,6.747614,1.408812,2.034735,0.033624,82.289950,True,DROPPED_STRUCTURAL

## UB2: rerun ubiquitination prediction on S1 survivors

In [11]:
ub2 = workflow.UB2(s1_conserved)
display(ub2)

,variant_id,protein_id,predictor,lysine_position,site,sequence_context,probability,threshold,is_positive
0,K132R__K153R,K132R__K153R,EUP,119,K119,MDELFSQVDEKRKKRDIPDYL,0.520525,0.4,True
1,K132R__K153R,K132R__K153R,EUP,185,K185,QEQLIPNLAMKEVIDAFISEN,0.495605,0.4,True
2,K132R__K153R,K132R__K153R,EUP,101,K101,VRAQQACIEAKHDKYMADMDE,0.487270,0.4,True
3,K132R__K153R,K132R__K153R,EUP,104,K104,QQACIEAKHDKYMADMDELFS,0.457296,0.4,True
4,K132R__K153R,K132R__K153R,EUP,122,K122,LFSQVDEKRKKRDIPDYLCGR,0.309721,0.4,False
...,...,...,...,...,...,...,...,...,...
118,K101R__K119R__K153R,K101R__K119R__K153R,EUP,122,K122,LFSQVDERRKKRDIPDYLCGK,0.309491,0.4,False
119,K101R__K119R__K153R,K101R__K119R__K153R,EUP,43,K43,IPSALRIAKKKRWNSIEERRI,0.287358,0.4,False
120,K101R__K119R__K153R,K101R__K119R__K153R,EUP,41,K41,DDIPSALRIAKKKRWNSIEER,0.272672,0.4,False
121,K101R__K119R__K153R,K101R__K119R__K153R,EUP,42,K42,DIPSALRIAKKKRWNSIEERR,0.235109,0.4,False
122,K101R__K119R__K153R,K101R__K119R__K153R,EUP,121,K121,ELFSQVDERRKKRDIPDYLCG,0.170323,0.4,False

## R2: final ranking

In [12]:
r2_all, optimized, needs_more = workflow.R2(up1, ub2, s1_conserved)

print("OPTIMIZED")
display(optimized)

print("NEEDS FURTHER OPTIMIZATION")
display(needs_more)

print("ALL RANKED")
display(r2_all)

OPTIMIZED

Empty DataFrame
Columns: [final_rank, variant_id, mutation_spec, mutation_count, structural_preservation_score, wt_positive_count, mutant_positive_count, targeted_wt_probability_sum, wt_positive_burden, mutant_positive_burden, ubiquitination_burden_reduction, ubiquitination_burden_reduction_fraction, removed_wt_sites, remaining_wt_positive_sites, new_positive_sites, new_positive_count, R2_group]
Index: []

NEEDS FURTHER OPTIMIZATION

,final_rank,variant_id,mutation_spec,mutation_count,structural_preservation_score,wt_positive_count,mutant_positive_count,targeted_wt_probability_sum,wt_positive_burden,mutant_positive_burden,ubiquitination_burden_reduction,ubiquitination_burden_reduction_fraction,removed_wt_sites,remaining_wt_positive_sites,new_positive_sites,new_positive_count,R2_group
0,1,K101R__K119R__K153R__K185R,K101R;K119R;K153R;K185R,4,0.777788,6,1,2.181079,3.042589,0.463341,2.579248,0.847715,K101;K119;K132;K153;K185,K104,,0,needs_further_optimization
1,2,K101R__K119R__K153R,K101R;K119R;K153R,3,0.764117,6,2,1.656216,3.042589,0.963199,2.079390,0.683428,K101;K119;K132;K153,K104;K185,,0,needs_further_optimization
2,3,K101R__K132R__K153R__K185R,K101R;K132R;K153R;K185R,4,0.833718,6,2,2.034130,3.042589,0.965246,2.077343,0.682755,K101;K132;K153;K185,K104;K119,,0,needs_further_optimization
3,4,K101R__K153R__K185R,K101R;K153R;K185R,3,0.807731,6,2,1.633465,3.042589,0.967446,2.075143,0.682032,K101;K132;K153;K185,K104;K119,,0,needs_further_optimization
4,5,K101R__K104R__K153R,K101R;K104R;K153R,3,0.848609,6,2,1.569445,3.042589,0.980875,2.061714,0.677618,K101;K104;K132;K153,K119;K185,,0,needs_further_optimization
5,6,K104R__K153R__K185R,K104R;K153R;K185R,3,0.840724,6,2,1.595086,3.042589,1.022918,2.019670,0.663800,K104;K132;K153;K185,K101;K119,,0,needs_further_optimization
6,7,K101R__K104R__K119R__K132R,K101R;K104R;K119R;K132R,4,0.791752,6,2,1.908347,3.042589,1.061210,1.981379,0.651215,K101;K104;K119;K132,K153;K185,,0,needs_further_optimization
7,8,K101R__K104R__K119R,K101R;K104R;K119R,3,0.847902,6,2,1.507681,3.042589,1.067824,1.974765,0.649041,K101;K104;K119;K132,K153;K185,,0,needs_further_optimization
8,9,K101R__K104R__K185R,K101R;K104R;K185R,3,0.817943,6,2,1.484930,3.042589,1.083573,1.959016,0.643865,K101;K104;K132;K185,K119;K153,,0,needs_further_optimization
9,10,K119R__K132R__K153R,K119R;K132R;K153R,3,0.808558,6,3,1.557658,3.042589,1.436063,1.606525,0.528013,K119;K132;K153,K101;K104;K185,,0,needs_further_optimization
10,11,K104R__K153R,K104R;K153R,2,0.816032,6,3,1.070222,3.042589,1.519870,1.522719,0.500468,K104;K132;K153,K101;K119;K185,,0,needs_further_optimization
11,12,K132R__K153R,K132R;K153R,2,0.861633,6,4,1.010044,3.042589,1.960696,1.081893,0.355583,K132;K153,K101;K104;K119;K185,,0,needs_further_optimization
12,13,K101R__K132R,K101R;K132R,2,0.840894,6,4,0.899888,3.042589,2.065138,0.977451,0.321256,K101;K132,K104;K119;K153;K185,,0,needs_further_optimization
13,14,K119R,K119R,1,0.853535,6,4,0.547615,3.042589,2.082117,0.960472,0.315676,K119;K132,K101;K104;K153;K185,,0,needs_further_optimization
14,15,K104R__K132R,K104R;K132R,2,0.814307,6,4,0.861510,3.042589,2.106996,0.935593,0.307499,K104;K132,K101;K119;K153;K185,,0,needs_further_optimization

ALL RANKED

,final_rank,variant_id,mutation_spec,mutation_count,structural_preservation_score,wt_positive_count,mutant_positive_count,targeted_wt_probability_sum,wt_positive_burden,mutant_positive_burden,ubiquitination_burden_reduction,ubiquitination_burden_reduction_fraction,removed_wt_sites,remaining_wt_positive_sites,new_positive_sites,new_positive_count,R2_group
0,1,K101R__K119R__K153R__K185R,K101R;K119R;K153R;K185R,4,0.777788,6,1,2.181079,3.042589,0.463341,2.579248,0.847715,K101;K119;K132;K153;K185,K104,,0,needs_further_optimization
1,2,K101R__K119R__K153R,K101R;K119R;K153R,3,0.764117,6,2,1.656216,3.042589,0.963199,2.079390,0.683428,K101;K119;K132;K153,K104;K185,,0,needs_further_optimization
2,3,K101R__K132R__K153R__K185R,K101R;K132R;K153R;K185R,4,0.833718,6,2,2.034130,3.042589,0.965246,2.077343,0.682755,K101;K132;K153;K185,K104;K119,,0,needs_further_optimization
3,4,K101R__K153R__K185R,K101R;K153R;K185R,3,0.807731,6,2,1.633465,3.042589,0.967446,2.075143,0.682032,K101;K132;K153;K185,K104;K119,,0,needs_further_optimization
4,5,K101R__K104R__K153R,K101R;K104R;K153R,3,0.848609,6,2,1.569445,3.042589,0.980875,2.061714,0.677618,K101;K104;K132;K153,K119;K185,,0,needs_further_optimization
5,6,K104R__K153R__K185R,K104R;K153R;K185R,3,0.840724,6,2,1.595086,3.042589,1.022918,2.019670,0.663800,K104;K132;K153;K185,K101;K119,,0,needs_further_optimization
6,7,K101R__K104R__K119R__K132R,K101R;K104R;K119R;K132R,4,0.791752,6,2,1.908347,3.042589,1.061210,1.981379,0.651215,K101;K104;K119;K132,K153;K185,,0,needs_further_optimization
7,8,K101R__K104R__K119R,K101R;K104R;K119R,3,0.847902,6,2,1.507681,3.042589,1.067824,1.974765,0.649041,K101;K104;K119;K132,K153;K185,,0,needs_further_optimization
8,9,K101R__K104R__K185R,K101R;K104R;K185R,3,0.817943,6,2,1.484930,3.042589,1.083573,1.959016,0.643865,K101;K104;K132;K185,K119;K153,,0,needs_further_optimization
9,10,K119R__K132R__K153R,K119R;K132R;K153R,3,0.808558,6,3,1.557658,3.042589,1.436063,1.606525,0.528013,K119;K132;K153,K101;K104;K185,,0,needs_further_optimization
10,11,K104R__K153R,K104R;K153R,2,0.816032,6,3,1.070222,3.042589,1.519870,1.522719,0.500468,K104;K132;K153,K101;K119;K185,,0,needs_further_optimization
11,12,K132R__K153R,K132R;K153R,2,0.861633,6,4,1.010044,3.042589,1.960696,1.081893,0.355583,K132;K153,K101;K104;K119;K185,,0,needs_further_optimization
12,13,K101R__K132R,K101R;K132R,2,0.840894,6,4,0.899888,3.042589,2.065138,0.977451,0.321256,K101;K132,K104;K119;K153;K185,,0,needs_further_optimization
13,14,K119R,K119R,1,0.853535,6,4,0.547615,3.042589,2.082117,0.960472,0.315676,K119;K132,K101;K104;K153;K185,,0,needs_further_optimization
14,15,K104R__K132R,K104R;K132R,2,0.814307,6,4,0.861510,3.042589,2.106996,0.935593,0.307499,K104;K132,K101;K119;K153;K185,,0,needs_further_optimization

## Inspect outputs

In [13]:
print("Tables:")
for path in sorted((RUN_ROOT / "storage" / "tables").glob("*.csv")):
    print(" -", path)

print("Mutant FASTAs:", len(list((RUN_ROOT / "storage" / "mutants" / "fastas").glob("*.fasta"))))
print("WT structure directory:", RUN_ROOT / "storage" / "structures" / "wt")
print("Mutant structure directory:", RUN_ROOT / "storage" / "structures" / "mutants")

Tables:
 - /content/drive/MyDrive/therapeutic_optimization_run/storage/tables/R1_structural_screen.csv
 - /content/drive/MyDrive/therapeutic_optimization_run/storage/tables/R2_all_ranked.csv
 - /content/drive/MyDrive/therapeutic_optimization_run/storage/tables/R2_needs_further_optimization.csv
 - /content/drive/MyDrive/therapeutic_optimization_run/storage/tables/R2_optimized.csv
 - /content/drive/MyDrive/therapeutic_optimization_run/storage/tables/S1_structural_metrics.csv
 - /content/drive/MyDrive/therapeutic_optimization_run/storage/tables/S1_structurally_conserved.csv
 - /content/drive/MyDrive/therapeutic_optimization_run/storage/tables/T2_mutation_manifest.csv
 - /content/drive/MyDrive/therapeutic_optimization_run/storage/tables/UB2_mutant_ubiquitination.csv
 - /content/drive/MyDrive/therapeutic_optimization_run/storage/tables/UP1_wt_ubiquitination.csv
Mutant FASTAs: 478
WT structure directory: /content/drive/MyDrive/therapeutic_optimization_run/storage/structures/wt
Mutant structure directory: /content/drive/MyDrive/therapeutic_optimization_run/storage/structures/mutants