# Therapeutic Optimization — Colab Runner

This notebook is intentionally lightweight. All reusable logic lives in `src/therapeutic_optimization/`.

Pipeline: **T1 → UP1 → T2 → S1 → R1 → UB2 → R2**.

Before publishing, replace the placeholder GitHub URL below with the real repository URL.

In [1]:
PROTEIN_ID = "my_protein"
WT_SEQUENCE = """PTAPPYDSLLVFDYEGGSGSGSGASRLNFGDDIPSALRIAKKKRWNSIEERRIHQESELHSYLSRLIAAERERELEECQRNHEGDEDDSHVRAQQACIEAKHDKYMADMDELFSQVDEKRKKRDIPDYLCGKISFELMREPCITPSGITYDRKDIEEHLQRVGHFDPVTRSPLTQEQLIPNLAMKEVIDAFISENGWVEDY"""

## Hyperparameters

`single` changes one selected lysine at a time. `combinatorial` generates orders 1 through `MAX_COMBINATION_ORDER` using every replacement amino acid listed in `REPLACEMENT_AAS`.

In [2]:
UBI_THRESHOLD = 0.36 ## least conservative true positive, false negative result F2 EUP presentation paper

MUTATION_MODE = "single"            # "single" or "combinatorial"
REPLACEMENT_AAS = ("R",)            # e.g. ("A", "R", "Q")
MAX_COMBINATION_ORDER = 4
MAX_VARIANTS = 5000

# S1 structural-preservation heuristic gates
GLOBAL_CA_RMSD_MAX = 1.0
LOCAL_MEAN_CA_DISPLACEMENT_MAX = 1.5
MUTATION_CA_DISPLACEMENT_MAX = 2.0
CONTACT_CHANGE_FRACTION_MAX = 0.10
MIN_MEAN_PLDDT = 70.0

## Runtime, dependencies, imports

Use a **GPU runtime**. EUP uses ESM2-3B and this implementation intentionally fails rather than silently falling back to a very slow CPU path.

In [3]:
from pathlib import Path
import os, shutil, subprocess, sys

REPO_URL = "https://github.com/juliaevizza/therapeutic_optimization.git"
REPO_DIR = Path("/content/therapeutic_optimization")

if not REPO_DIR.exists():
    subprocess.run(["git", "clone", "--depth", "1", REPO_URL, str(REPO_DIR)], check=True)
os.chdir(REPO_DIR)
print("Repository ready:", REPO_DIR)

# Run this after REPO_URL is configured and the repository has been cloned.
if REPO_DIR.exists():
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", "-e", f"{REPO_DIR}[eup]"], check=True)

    if shutil.which("git-lfs") is None:
        subprocess.run(["apt-get", "-qq", "update"], check=True)
        subprocess.run(["apt-get", "-qq", "install", "-y", "git-lfs"], check=True)
    subprocess.run(["git", "lfs", "install"], check=True)

    if shutil.which("colabfold_batch") is None:
        print("colabfold_batch not found. Installing the current CUDA 12 ColabFold stack...")
        subprocess.run([
            sys.executable, "-m", "pip", "install", "-q",
            "colabfold[alphafold,openmm]", "jax[cuda12]", "openmm[cuda12]"
        ], check=True)

    subprocess.run([sys.executable, str(REPO_DIR / "scripts" / "check_environment.py")], check=False)

Repository ready: /content/therapeutic_optimization
colabfold_batch not found. Installing the current CUDA 12 ColabFold stack...

## Choose where run outputs live

Set `SAVE_TO_DRIVE = True` if you want the run to survive Colab shutdown. The package code still runs from GitHub; only `storage/` outputs go into this run directory.

In [4]:
SAVE_TO_DRIVE = True

if SAVE_TO_DRIVE:
    from google.colab import drive
    drive.mount("/content/drive")
    RUN_ROOT = Path("/content/drive/MyDrive/therapeutic_optimization_run")
else:
    RUN_ROOT = Path("/content/therapeutic_optimization_run")

RUN_ROOT.mkdir(parents=True, exist_ok=True)
print("Run root:", RUN_ROOT)

Mounted at /content/drive
Run root: /content/drive/MyDrive/therapeutic_optimization_run

## Build the workflow

In [5]:
import sys
if 'therapeutic_optimization' in sys.modules:
    del sys.modules['therapeutic_optimization']
if "/content/therapeutic_optimization/src" not in sys.path:
    sys.path.insert(0, "/content/therapeutic_optimization/src")

from therapeutic_optimization.config import (
    MutationConfig,
    PredictorConfig,
    StructuralThresholds,
    WorkflowConfig,
)
from therapeutic_optimization.workflow import OptimizationWorkflow
from pathlib import Path

config = WorkflowConfig(
    mutation=MutationConfig(
        threshold=UBI_THRESHOLD,
        mode=MUTATION_MODE,
        replacement_aas=REPLACEMENT_AAS,
        max_combination_order=MAX_COMBINATION_ORDER,
        max_variants=MAX_VARIANTS,
    ),
    ubiquitination=PredictorConfig(
        name="eup",
        threshold=UBI_THRESHOLD,
        eup_repo_dir=Path("/content/external/EUP"),
        model_cache_dir=Path("/content/huggingface"),
    ),
    structural_thresholds=StructuralThresholds(
        global_ca_rmsd_max=GLOBAL_CA_RMSD_MAX,
        local_mean_ca_displacement_max=LOCAL_MEAN_CA_DISPLACEMENT_MAX,
        mutation_ca_displacement_max=MUTATION_CA_DISPLACEMENT_MAX,
        contact_change_fraction_max=CONTACT_CHANGE_FRACTION_MAX,
        min_mean_plddt=MIN_MEAN_PLDDT,
    ),
)

workflow = OptimizationWorkflow(RUN_ROOT, config)

## T1: input → WT FASTA

In [6]:
t1 = workflow.T1(WT_SEQUENCE, PROTEIN_ID)
t1

{'protein_id': 'my_protein',
 'sequence_length': 201,
 'wt_fasta': '/content/drive/MyDrive/therapeutic_optimization_run/storage/inputs/wt_input.fasta',
 'created_at_utc': '2026-09-03T00:02:11.604076+00:00'}

## UP1: WT ubiquitination prediction

In [7]:
up1 = workflow.UP1()
display(up1)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/779 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/95.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/93.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

pytorch_model.bin.index.json:   0%|          | 0.00/55.5k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

model.safetensors.index.json:   0%|          | 0.00/58.0k [00:00<?, ?B/s]

Loading weights:   0%|          | 0/582 [00:00<?, ?it/s]

[transformers] EsmModel LOAD REPORT from: facebook/esm2_t36_3B_UR50D
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.bias        | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.decoder.weight    | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
pooler.dense.weight       | MISSING    |
pooler.dense.bias         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

,variant_id,protein_id,predictor,lysine_position,site,sequence_context,probability,threshold,is_positive
0,WT,my_protein,EUP,153,K153,ITPSGITYDRKDIEEHLQRVG,0.609378,0.36,True
1,WT,my_protein,EUP,119,K119,MDELFSQVDEKRKKRDIPDYL,0.547615,0.36,True
2,WT,my_protein,EUP,185,K185,QEQLIPNLAMKEVIDAFISEN,0.524864,0.36,True
3,WT,my_protein,EUP,101,K101,VRAQQACIEAKHDKYMADMDE,0.499223,0.36,True
4,WT,my_protein,EUP,104,K104,QQACIEAKHDKYMADMDELFS,0.460844,0.36,True
5,WT,my_protein,EUP,132,K132,KRDIPDYLCGKISFELMREPC,0.400665,0.36,True
6,WT,my_protein,EUP,122,K122,LFSQVDEKRKKRDIPDYLCGK,0.332685,0.36,False
7,WT,my_protein,EUP,43,K43,IPSALRIAKKKRWNSIEERRI,0.302615,0.36,False
8,WT,my_protein,EUP,41,K41,DDIPSALRIAKKKRWNSIEER,0.288181,0.36,False
9,WT,my_protein,EUP,42,K42,DIPSALRIAKKKRWNSIEERR,0.245417,0.36,False
10,WT,my_protein,EUP,121,K121,ELFSQVDEKRKKRDIPDYLCG,0.176179,0.36,False

## T2: generate mutant FASTAs

In [8]:
t2 = workflow.T2(up1)
print(f"Generated {len(t2)} mutant(s).")
display(t2)

Generated 56 mutant(s).

,variant_id,mutation_spec,mutation_count,source_sites,replacement_aas,sequence_length,fasta_path,status,error
0,K101R,K101R,1,K101,R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
1,K104R,K104R,1,K104,R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
2,K119R,K119R,1,K119,R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
3,K132R,K132R,1,K132,R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
4,K153R,K153R,1,K153,R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
5,K185R,K185R,1,K185,R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
6,K101R__K104R,K101R;K104R,2,K101;K104,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
7,K101R__K119R,K101R;K119R,2,K101;K119,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
8,K101R__K132R,K101R;K132R,2,K101;K132,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
9,K101R__K153R,K101R;K153R,2,K101;K153,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
10,K101R__K185R,K101R;K185R,2,K101;K185,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
11,K104R__K119R,K104R;K119R,2,K104;K119,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
12,K104R__K132R,K104R;K132R,2,K104;K132,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
13,K104R__K153R,K104R;K153R,2,K104;K153,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
14,K104R__K185R,K104R;K185R,2,K104;K185,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
15,K119R__K132R,K119R;K132R,2,K119;K132,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
16,K119R__K153R,K119R;K153R,2,K119;K153,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
17,K119R__K185R,K119R;K185R,2,K119;K185,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
18,K132R__K153R,K132R;K153R,2,K132;K153,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
19,K132R__K185R,K132R;K185R,2,K132;K185,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
20,K153R__K185R,K153R;K185R,2,K153;K185,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
21,K101R__K104R__K119R,K101R;K104R;K119R,3,K101;K104;K119,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
22,K101R__K104R__K132R,K101R;K104R;K132R,3,K101;K104;K132,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
23,K101R__K104R__K153R,K101R;K104R;K153R,3,K101;K104;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
24,K101R__K104R__K185R,K101R;K104R;K185R,3,K101;K104;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
25,K101R__K119R__K132R,K101R;K119R;K132R,3,K101;K119;K132,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
26,K101R__K119R__K153R,K101R;K119R;K153R,3,K101;K119;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
27,K101R__K119R__K185R,K101R;K119R;K185R,3,K101;K119;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
28,K101R__K132R__K153R,K101R;K132R;K153R,3,K101;K132;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
29,K101R__K132R__K185R,K101R;K132R;K185R,3,K101;K132;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
30,K101R__K153R__K185R,K101R;K153R;K185R,3,K101;K153;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
31,K104R__K119R__K132R,K104R;K119R;K132R,3,K104;K119;K132,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
32,K104R__K119R__K153R,K104R;K119R;K153R,3,K104;K119;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
33,K104R__K119R__K185R,K104R;K119R;K185R,3,K104;K119;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
34,K104R__K132R__K153R,K104R;K132R;K153R,3,K104;K132;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
35,K104R__K132R__K185R,K104R;K132R;K185R,3,K104;K132;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
36,K104R__K153R__K185R,K104R;K153R;K185R,3,K104;K153;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
37,K119R__K132R__K153R,K119R;K132R;K153R,3,K119;K132;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
38,K119R__K132R__K185R,K119R;K132R;K185R,3,K119;K132;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
39,K119R__K153R__K185R,K119R;K153R;K185R,3,K119;K153;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
40,K132R__K153R__K185R,K132R;K153R;K185R,3,K132;K153;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
41,K101R__K104R__K119R__K132R,K101R;K104R;K119R;K132R,4,K101;K104;K119;K132,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
42,K101R__K104R__K119R__K153R,K101R;K104R;K119R;K153R,4,K101;K104;K119;K153,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
43,K101R__K104R__K119R__K185R,K101R;K104R;K119R;K185R,4,K101;K104;K119;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
44,K101R__K104R__K132R__K153R,K101R;K104R;K132R;K153R,4,K101;K104;K132;K153,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
45,K101R__K104R__K132R__K185R,K101R;K104R;K132R;K185R,4,K101;K104;K132;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
46,K101R__K104R__K153R__K185R,K101R;K104R;K153R;K185R,4,K101;K104;K153;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
47,K101R__K119R__K132R__K153R,K101R;K119R;K132R;K153R,4,K101;K119;K132;K153,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
48,K101R__K119R__K132R__K185R,K101R;K119R;K132R;K185R,4,K101;K119;K132;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
49,K101R__K119R__K153R__K185R,K101R;K119R;K153R;K185R,4,K101;K119;K153;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
50,K101R__K132R__K153R__K185R,K101R;K132R;K153R;K185R,4,K101;K132;K153;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
51,K104R__K119R__K132R__K153R,K104R;K119R;K132R;K153R,4,K104;K119;K132;K153,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
52,K104R__K119R__K132R__K185R,K104R;K119R;K132R;K185R,4,K104;K119;K132;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
53,K104R__K119R__K153R__K185R,K104R;K119R;K153R;K185R,4,K104;K119;K153;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
54,K104R__K132R__K153R__K185R,K104R;K132R;K153R;K185R,4,K104;K132;K153;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None
55,K119R__K132R__K153R__K185R,K119R;K132R;K153R;K185R,4,K119;K132;K153;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None

# P1: perplexity

In [ ]:
from therapeutic_optimization.esm2_analysis import run_esm2_analysis

t2 = workflow.T2(up1)
esm2_results = run_esm2_analysis(t2, workflow.paths)

## S1: structure prediction + preservation screen

This is the expensive structure stage. Every T2 mutant is predicted and compared with WT.

In [9]:
s1_metrics, s1_conserved = workflow.S1(t2, predict_structures=True)
print(f"Structurally conserved: {len(s1_conserved)} / {len(s1_metrics)}")
display(s1_metrics)
display(s1_conserved)

Structurally conserved: 16 / 56

,variant_id,mutation_spec,mutation_count,source_sites,replacement_aas,sequence_length,fasta_path,status,error,global_ca_rmsd,...,mean_centroid_distance_change,mean_residue_volume_change,per_residue_csv,displacement_plot,wt_structure,mutant_structure,analysis_status,analysis_error,structure_pass,structural_preservation_score
0,K101R,K101R,1,K101,R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.172226,...,0.170307,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.807547
1,K104R,K104R,1,K104,R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.043241,...,0.128237,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.772437
2,K119R,K119R,1,K119,R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.666752,...,-0.034152,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.851707
3,K132R,K132R,1,K132,R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.197168,...,-0.070995,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.775455
4,K153R,K153R,1,K153,R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,6.884772,...,0.493323,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.594432
5,K185R,K185R,1,K185,R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.616363,...,-0.044704,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.655386
6,K101R__K104R,K101R;K104R,2,K101;K104,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.176593,...,0.313578,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.779672
7,K101R__K119R,K101R;K119R,2,K101;K119,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.035020,...,0.047244,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.795599
8,K101R__K132R,K101R;K132R,2,K101;K132,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.776080,...,0.137578,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.840352
9,K101R__K153R,K101R;K153R,2,K101;K153,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.327859,...,0.146115,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.772675
10,K101R__K185R,K101R;K185R,2,K101;K185,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,2.202084,...,0.177637,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.674495
11,K104R__K119R,K104R;K119R,2,K104;K119,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.264763,...,0.283454,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.762573
12,K104R__K132R,K104R;K132R,2,K104;K132,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.846244,...,0.171561,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.820977
13,K104R__K153R,K104R;K153R,2,K104;K153,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.845833,...,0.057438,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.819667
14,K104R__K185R,K104R;K185R,2,K104;K185,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,7.061669,...,0.101924,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.590661
15,K119R__K132R,K119R;K132R,2,K119;K132,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,6.989898,...,-0.260716,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.553890
16,K119R__K153R,K119R;K153R,2,K119;K153,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.344323,...,0.134658,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.735603
17,K119R__K185R,K119R;K185R,2,K119;K185,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.214720,...,-0.099609,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.735238
18,K132R__K153R,K132R;K153R,2,K132;K153,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.584943,...,0.099134,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.862666
19,K132R__K185R,K132R;K185R,2,K132;K185,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.133672,...,-0.216970,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.761311
20,K153R__K185R,K153R;K185R,2,K153;K185,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.357856,...,-0.061865,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.749301
21,K101R__K104R__K119R,K101R;K104R;K119R,3,K101;K104;K119,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.679258,...,0.112782,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.845673
22,K101R__K104R__K132R,K101R;K104R;K132R,3,K101;K104;K132,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.369801,...,0.131342,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.753871
23,K101R__K104R__K153R,K101R;K104R;K153R,3,K101;K104;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.759983,...,0.115680,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.847840
24,K101R__K104R__K185R,K101R;K104R;K185R,3,K101;K104;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.810393,...,0.144027,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.819597
25,K101R__K119R__K132R,K101R;K119R;K132R,3,K101;K119;K132,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.728508,...,0.297593,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.680262
26,K101R__K119R__K153R,K101R;K119R;K153R,3,K101;K119;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.890227,...,0.091724,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.767060
27,K101R__K119R__K185R,K101R;K119R;K185R,3,K101;K119;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.189999,...,0.095829,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.760487
28,K101R__K132R__K153R,K101R;K132R;K153R,3,K101;K132;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.976680,...,0.135159,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.663062
29,K101R__K132R__K185R,K101R;K132R;K185R,3,K101;K132;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.470899,...,0.023792,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.675603
30,K101R__K153R__K185R,K101R;K153R;K185R,3,K101;K153;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.985527,...,0.017950,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.807777
31,K104R__K119R__K132R,K104R;K119R;K132R,3,K104;K119;K132,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.318396,...,0.029369,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.744349
32,K104R__K119R__K153R,K104R;K119R;K153R,3,K104;K119;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.202824,...,0.119191,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.746233
33,K104R__K119R__K185R,K104R;K119R;K185R,3,K104;K119;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.234202,...,0.011719,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.724144
34,K104R__K132R__K153R,K104R;K132R;K153R,3,K104;K132;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.481655,...,0.016488,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.729620
35,K104R__K132R__K185R,K104R;K132R;K185R,3,K104;K132;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.711023,...,-0.014410,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.654637
36,K104R__K153R__K185R,K104R;K153R;K185R,3,K104;K153;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.715787,...,-0.026064,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.839838
37,K119R__K132R__K153R,K119R;K132R;K153R,3,K119;K132;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.919341,...,0.092464,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.805952
38,K119R__K132R__K185R,K119R;K132R;K185R,3,K119;K132;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,6.825962,...,-0.186726,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.540143
39,K119R__K153R__K185R,K119R;K153R;K185R,3,K119;K153;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.055366,...,-0.112794,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.795256
40,K132R__K153R__K185R,K132R;K153R;K185R,3,K132;K153;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.987396,...,-0.128152,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.802508
41,K101R__K104R__K119R__K132R,K101R;K104R;K119R;K132R,4,K101;K104;K119;K132,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.856160,...,0.143145,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.795780
42,K101R__K104R__K119R__K153R,K101R;K104R;K119R;K153R,4,K101;K104;K119;K153,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.266894,...,0.103832,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.742522
43,K101R__K104R__K119R__K185R,K101R;K104R;K119R;K185R,4,K101;K104;K119;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.009487,...,0.165823,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.798593
44,K101R__K104R__K132R__K153R,K101R;K104R;K132R;K153R,4,K101;K104;K132;K153,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.170245,...,0.179243,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.779247
45,K101R__K104R__K132R__K185R,K101R;K104R;K132R;K185R,4,K101;K104;K132;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.289575,...,0.158340,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.764277
46,K101R__K104R__K153R__K185R,K101R;K104R;K153R;K185R,4,K101;K104;K153;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.110196,...,0.112695,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.740412
47,K101R__K119R__K132R__K153R,K101R;K119R;K132R;K153R,4,K101;K119;K132;K153,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.301823,...,0.178284,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.736970
48,K101R__K119R__K132R__K185R,K101R;K119R;K132R;K185R,4,K101;K119;K132;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,6.738718,...,-0.017789,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.534335
49,K101R__K119R__K153R__K185R,K101R;K119R;K153R;K185R,4,K101;K119;K153;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.916555,...,0.354920,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.776114
50,K101R__K132R__K153R__K185R,K101R;K132R;K153R;K185R,4,K101;K132;K153;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.760202,...,0.069703,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.838986
51,K104R__K119R__K132R__K153R,K104R;K119R;K132R;K153R,4,K104;K119;K132;K153,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,1.285723,...,0.010302,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,False,0.782410

,variant_id,mutation_spec,mutation_count,source_sites,replacement_aas,sequence_length,fasta_path,status,error,global_ca_rmsd,...,mean_centroid_distance_change,mean_residue_volume_change,per_residue_csv,displacement_plot,wt_structure,mutant_structure,analysis_status,analysis_error,structure_pass,structural_preservation_score
18,K132R__K153R,K132R;K153R,2,K132;K153,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.584943,...,0.099134,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.862666
2,K119R,K119R,1,K119,R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.666752,...,-0.034152,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.851707
23,K101R__K104R__K153R,K101R;K104R;K153R,3,K101;K104;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.759983,...,0.115680,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.847840
21,K101R__K104R__K119R,K101R;K104R;K119R,3,K101;K104;K119,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.679258,...,0.112782,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.845673
8,K101R__K132R,K101R;K132R,2,K101;K132,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.776080,...,0.137578,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.840352
36,K104R__K153R__K185R,K104R;K153R;K185R,3,K104;K153;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.715787,...,-0.026064,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.839838
50,K101R__K132R__K153R__K185R,K101R;K132R;K153R;K185R,4,K101;K132;K153;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.760202,...,0.069703,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.838986
12,K104R__K132R,K104R;K132R,2,K104;K132,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.846244,...,0.171561,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.820977
13,K104R__K153R,K104R;K153R,2,K104;K153,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.845833,...,0.057438,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.819667
24,K101R__K104R__K185R,K101R;K104R;K185R,3,K101;K104;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.810393,...,0.144027,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.819597
30,K101R__K153R__K185R,K101R;K153R;K185R,3,K101;K153;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.985527,...,0.017950,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.807777
37,K119R__K132R__K153R,K119R;K132R;K153R,3,K119;K132;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.919341,...,0.092464,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.805952
40,K132R__K153R__K185R,K132R;K153R;K185R,3,K132;K153;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.987396,...,-0.128152,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.802508
41,K101R__K104R__K119R__K132R,K101R;K104R;K119R;K132R,4,K101;K104;K119;K132,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.856160,...,0.143145,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.795780
49,K101R__K119R__K153R__K185R,K101R;K119R;K153R;K185R,4,K101;K119;K153;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.916555,...,0.354920,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.776114
26,K101R__K119R__K153R,K101R;K119R;K153R,3,K101;K119;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,0.890227,...,0.091724,13.0,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,True,0.767060

## R1: record structural dropouts

In [10]:
r1 = workflow.R1(t2, s1_metrics)
display(r1)

,variant_id,mutation_spec,mutation_count,source_sites,replacement_aas,sequence_length,fasta_path,status,error,analysis_status,analysis_error,structure_pass,structural_preservation_score,global_ca_rmsd,local_mean_ca_displacement,mutation_ca_displacement_max,global_contact_change_fraction,mutant_mean_plddt,dropped_after_S1,R1_status
0,K132R__K153R,K132R;K153R,2,K132;K153,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,True,0.862666,0.584943,0.285371,0.345519,0.007663,82.561990,False,ADVANCE_TO_UB2
1,K119R,K119R,1,K119,R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,True,0.851707,0.666752,0.291030,0.428449,0.006386,82.795970,False,ADVANCE_TO_UB2
2,K101R__K104R__K153R,K101R;K104R;K153R,3,K101;K104;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,True,0.847840,0.759983,0.230598,0.393218,0.006394,82.633184,False,ADVANCE_TO_UB2
3,K101R__K104R__K119R,K101R;K104R;K119R,3,K101;K104;K119,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,True,0.845673,0.679258,0.336993,0.468139,0.006394,82.932786,False,ADVANCE_TO_UB2
4,K101R__K132R,K101R;K132R,2,K101;K132,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,True,0.840352,0.776080,0.320692,0.459594,0.003836,83.077960,False,ADVANCE_TO_UB2
5,K104R__K153R__K185R,K104R;K153R;K185R,3,K104;K153;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,True,0.839838,0.715787,0.344651,0.534151,0.003841,82.471095,False,ADVANCE_TO_UB2
6,K101R__K132R__K153R__K185R,K101R;K132R;K153R;K185R,4,K101;K132;K153;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,True,0.838986,0.760202,0.342165,0.448165,0.005122,82.673682,False,ADVANCE_TO_UB2
7,K104R__K132R,K104R;K132R,2,K104;K132,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,True,0.820977,0.846244,0.368082,0.614930,0.003846,82.366617,False,ADVANCE_TO_UB2
8,K104R__K153R,K104R;K153R,2,K104;K153,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,True,0.819667,0.845833,0.422240,0.562202,0.005128,82.818856,False,ADVANCE_TO_UB2
9,K101R__K104R__K185R,K101R;K104R;K185R,3,K101;K104;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,True,0.819597,0.810393,0.443815,0.571654,0.007663,83.234577,False,ADVANCE_TO_UB2
10,K101R__K153R__K185R,K101R;K153R;K185R,3,K101;K153;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,True,0.807777,0.985527,0.394561,0.458155,0.008940,82.240697,False,ADVANCE_TO_UB2
11,K119R__K132R__K153R,K119R;K132R;K153R,3,K119;K132;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,True,0.805952,0.919341,0.361414,0.739890,0.005122,82.048209,False,ADVANCE_TO_UB2
12,K132R__K153R__K185R,K132R;K153R;K185R,3,K132;K153;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,True,0.802508,0.987396,0.418400,0.540307,0.007653,81.904826,False,ADVANCE_TO_UB2
13,K101R__K104R__K119R__K132R,K101R;K104R;K119R;K132R,4,K101;K104;K119;K132,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,True,0.795780,0.856160,0.490740,0.862573,0.007663,82.451891,False,ADVANCE_TO_UB2
14,K101R__K119R__K153R__K185R,K101R;K119R;K153R;K185R,4,K101;K119;K153;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,True,0.776114,0.916555,0.507166,1.023779,0.011509,82.139403,False,ADVANCE_TO_UB2
15,K101R__K119R__K153R,K101R;K119R;K153R,3,K101;K119;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,True,0.767060,0.890227,0.593762,1.217771,0.007653,82.104129,False,ADVANCE_TO_UB2
16,K101R,K101R,1,K101,R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.807547,1.172226,0.210023,0.273624,0.012706,82.579204,True,DROPPED_STRUCTURAL
17,K119R__K132R__K153R__K185R,K119R;K132R;K153R;K185R,4,K119;K132;K153;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.800037,1.045942,0.411903,0.587668,0.005122,83.298060,True,DROPPED_STRUCTURAL
18,K101R__K104R__K119R__K185R,K101R;K104R;K119R;K185R,4,K101;K104;K119;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.798593,1.009487,0.381435,0.555963,0.011465,82.116716,True,DROPPED_STRUCTURAL
19,K101R__K119R,K101R;K119R,2,K101;K119,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.795599,1.035020,0.428480,0.559933,0.010230,82.946468,True,DROPPED_STRUCTURAL
20,K119R__K153R__K185R,K119R;K153R;K185R,3,K119;K153;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.795256,1.055366,0.342517,0.637021,0.010204,82.840995,True,DROPPED_STRUCTURAL
21,K104R__K119R__K132R__K153R,K104R;K119R;K132R;K153R,4,K104;K119;K132;K153,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.782410,1.285723,0.308930,0.419459,0.012723,82.636716,True,DROPPED_STRUCTURAL
22,K101R__K104R,K101R;K104R,2,K101;K104,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.779672,1.176593,0.420989,0.488580,0.015248,82.537065,True,DROPPED_STRUCTURAL
23,K101R__K104R__K132R__K153R,K101R;K104R;K132R;K153R,4,K101;K104;K132;K153,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.779247,1.170245,0.342409,0.595963,0.015228,82.062786,True,DROPPED_STRUCTURAL
24,K132R,K132R,1,K132,R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.775455,1.197168,0.444246,0.506794,0.015228,82.678209,True,DROPPED_STRUCTURAL
25,K101R__K153R,K101R;K153R,2,K101;K153,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.772675,1.327859,0.312460,0.470910,0.015209,82.523085,True,DROPPED_STRUCTURAL
26,K104R,K104R,1,K104,R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.772437,1.043241,0.613879,0.797481,0.007673,82.616617,True,DROPPED_STRUCTURAL
27,K104R__K132R__K153R__K185R,K104R;K132R;K153R;K185R,4,K104;K132;K153;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.768536,1.243200,0.455519,0.631421,0.011465,83.129851,True,DROPPED_STRUCTURAL
28,K101R__K104R__K132R__K185R,K101R;K104R;K132R;K185R,4,K101;K104;K132;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.764277,1.289575,0.414189,0.554102,0.016518,82.535124,True,DROPPED_STRUCTURAL
29,K104R__K119R,K104R;K119R,2,K104;K119,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.762573,1.264763,0.542561,0.689336,0.003841,81.763831,True,DROPPED_STRUCTURAL
30,K132R__K185R,K132R;K185R,2,K132;K185,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.761311,1.133672,0.617348,0.792200,0.008917,82.180796,True,DROPPED_STRUCTURAL
31,K101R__K119R__K185R,K101R;K119R;K185R,3,K101;K119;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.760487,1.189999,0.494413,0.806347,0.011480,82.122189,True,DROPPED_STRUCTURAL
32,K101R__K104R__K132R,K101R;K104R;K132R,3,K101;K104;K132,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.753871,1.369801,0.489209,0.669087,0.007643,82.281244,True,DROPPED_STRUCTURAL
33,K153R__K185R,K153R;K185R,2,K153;K185,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.749301,1.357856,0.510675,0.517417,0.018987,81.995025,True,DROPPED_STRUCTURAL
34,K104R__K119R__K153R,K104R;K119R;K153R,3,K104;K119;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.746233,1.202824,0.671871,0.872215,0.008940,81.928557,True,DROPPED_STRUCTURAL
35,K104R__K119R__K132R,K104R;K119R;K132R,3,K104;K119;K132,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.744349,1.318396,0.504462,0.865830,0.010178,81.644527,True,DROPPED_STRUCTURAL
36,K101R__K104R__K119R__K153R,K101R;K104R;K119R;K153R,4,K101;K104;K119;K153,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.742522,1.266894,0.671842,0.937761,0.002564,81.726418,True,DROPPED_STRUCTURAL
37,K101R__K104R__K153R__K185R,K101R;K104R;K153R;K185R,4,K101;K104;K153;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.740412,1.110196,0.759720,1.134265,0.006394,82.593284,True,DROPPED_STRUCTURAL
38,K101R__K119R__K132R__K153R,K101R;K119R;K132R;K153R,4,K101;K119;K132;K153,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.736970,1.301823,0.597599,0.930256,0.011465,82.484925,True,DROPPED_STRUCTURAL
39,K104R__K119R__K153R__K185R,K104R;K119R;K153R;K185R,4,K104;K119;K153;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.736340,1.276616,0.578260,0.912232,0.016497,82.330647,True,DROPPED_STRUCTURAL
40,K119R__K153R,K119R;K153R,2,K119;K153,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.735603,1.344323,0.525707,0.840373,0.016497,81.799154,True,DROPPED_STRUCTURAL
41,K119R__K185R,K119R;K185R,2,K119;K185,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.735238,1.214720,0.715643,0.962064,0.012755,82.638756,True,DROPPED_STRUCTURAL
42,K104R__K132R__K153R,K104R;K132R;K153R,3,K104;K132;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.729620,1.481655,0.469227,0.724795,0.018987,82.147164,True,DROPPED_STRUCTURAL
43,K104R__K119R__K185R,K104R;K119R;K185R,3,K104;K119;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.724144,1.234202,0.878665,1.090912,0.003846,82.266667,True,DROPPED_STRUCTURAL
44,K101R__K119R__K132R,K101R;K119R;K132R,3,K101;K119;K132,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.680262,1.728508,0.638781,1.052479,0.015209,81.765622,True,DROPPED_STRUCTURAL
45,K101R__K132R__K185R,K101R;K132R;K185R,3,K101;K132;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.675603,1.470899,0.882007,1.288980,0.017722,81.831990,True,DROPPED_STRUCTURAL
46,K101R__K185R,K101R;K185R,2,K101;K185,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.674495,2.202084,0.566183,0.638532,0.018987,81.577363,True,DROPPED_STRUCTURAL
47,K101R__K132R__K153R,K101R;K132R;K153R,3,K101;K132;K153,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.663062,1.976680,0.619836,0.900866,0.017677,82.386169,True,DROPPED_STRUCTURAL
48,K185R,K185R,1,K185,R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.655386,1.616363,1.030250,1.001966,0.030075,82.939602,True,DROPPED_STRUCTURAL
49,K104R__K132R__K185R,K104R;K132R;K185R,3,K104;K132;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.654637,1.711023,0.862563,1.264037,0.018987,82.716368,True,DROPPED_STRUCTURAL
50,K153R,K153R,1,K153,R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.594432,6.884772,1.135682,1.160991,0.036070,82.131443,True,DROPPED_STRUCTURAL
51,K104R__K185R,K104R;K185R,2,K104;K185,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.590661,7.061669,1.207537,1.447948,0.021465,82.512736,True,DROPPED_STRUCTURAL
52,K119R__K132R,K119R;K132R,2,K119;K132,R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.553890,6.989898,1.488954,1.819884,0.020177,82.161990,True,DROPPED_STRUCTURAL
53,K119R__K132R__K185R,K119R;K132R;K185R,3,K119;K132;K185,R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.540143,6.825962,1.589493,1.789275,0.028858,82.215821,True,DROPPED_STRUCTURAL
54,K104R__K119R__K132R__K185R,K104R;K119R;K132R;K185R,4,K104;K119;K132;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.539480,6.966704,1.485578,1.923125,0.028858,81.766318,True,DROPPED_STRUCTURAL
55,K101R__K119R__K132R__K185R,K101R;K119R;K132R;K185R,4,K101;K119;K132;K185,R;R;R;R,201,/content/drive/MyDrive/therapeutic_optimizatio...,PASS,None,PASS,None,False,0.534335,6.738718,1.397268,2.020476,0.036070,82.289950,True,DROPPED_STRUCTURAL

## UB2: rerun ubiquitination prediction on S1 survivors

In [11]:
ub2 = workflow.UB2(s1_conserved)
display(ub2)

,variant_id,protein_id,predictor,lysine_position,site,sequence_context,probability,threshold,is_positive
0,K132R__K153R,K132R__K153R,EUP,119,K119,MDELFSQVDEKRKKRDIPDYL,0.520525,0.36,True
1,K132R__K153R,K132R__K153R,EUP,185,K185,QEQLIPNLAMKEVIDAFISEN,0.495605,0.36,True
2,K132R__K153R,K132R__K153R,EUP,101,K101,VRAQQACIEAKHDKYMADMDE,0.487270,0.36,True
3,K132R__K153R,K132R__K153R,EUP,104,K104,QQACIEAKHDKYMADMDELFS,0.457296,0.36,True
4,K132R__K153R,K132R__K153R,EUP,122,K122,LFSQVDEKRKKRDIPDYLCGR,0.309721,0.36,False
...,...,...,...,...,...,...,...,...,...
126,K101R__K119R__K153R,K101R__K119R__K153R,EUP,122,K122,LFSQVDERRKKRDIPDYLCGK,0.309491,0.36,False
127,K101R__K119R__K153R,K101R__K119R__K153R,EUP,43,K43,IPSALRIAKKKRWNSIEERRI,0.287358,0.36,False
128,K101R__K119R__K153R,K101R__K119R__K153R,EUP,41,K41,DDIPSALRIAKKKRWNSIEER,0.272672,0.36,False
129,K101R__K119R__K153R,K101R__K119R__K153R,EUP,42,K42,DIPSALRIAKKKRWNSIEERR,0.235109,0.36,False
130,K101R__K119R__K153R,K101R__K119R__K153R,EUP,121,K121,ELFSQVDERRKKRDIPDYLCG,0.170323,0.36,False

## R2: final ranking

In [12]:
r2_all, optimized, needs_more = workflow.R2(up1, ub2, s1_conserved)

print("OPTIMIZED")
display(optimized)

print("NEEDS FURTHER OPTIMIZATION")
display(needs_more)

print("ALL RANKED")
display(r2_all)

OPTIMIZED

Empty DataFrame
Columns: [final_rank, variant_id, mutation_spec, mutation_count, structural_preservation_score, wt_positive_count, mutant_positive_count, targeted_wt_probability_sum, wt_positive_burden, mutant_positive_burden, ubiquitination_burden_reduction, ubiquitination_burden_reduction_fraction, removed_wt_sites, remaining_wt_positive_sites, new_positive_sites, new_positive_count, R2_group]
Index: []

NEEDS FURTHER OPTIMIZATION

,final_rank,variant_id,mutation_spec,mutation_count,structural_preservation_score,wt_positive_count,mutant_positive_count,targeted_wt_probability_sum,wt_positive_burden,mutant_positive_burden,ubiquitination_burden_reduction,ubiquitination_burden_reduction_fraction,removed_wt_sites,remaining_wt_positive_sites,new_positive_sites,new_positive_count,R2_group
0,1,K101R__K119R__K153R__K185R,K101R;K119R;K153R;K185R,4,0.776114,6,2,2.181079,3.042589,0.847840,2.194749,0.721343,K101;K119;K153;K185,K104;K132,,0,needs_further_optimization
1,2,K101R__K132R__K153R__K185R,K101R;K132R;K153R;K185R,4,0.838986,6,2,2.034130,3.042589,0.965246,2.077343,0.682755,K101;K132;K153;K185,K104;K119,,0,needs_further_optimization
2,3,K101R__K104R__K119R__K132R,K101R;K104R;K119R;K132R,4,0.795780,6,2,1.908347,3.042589,1.061210,1.981379,0.651215,K101;K104;K119;K132,K153;K185,,0,needs_further_optimization
3,4,K101R__K119R__K153R,K101R;K119R;K153R,3,0.767060,6,3,1.656216,3.042589,1.352576,1.690013,0.555452,K101;K119;K153,K104;K132;K185,,0,needs_further_optimization
4,5,K101R__K153R__K185R,K101R;K153R;K185R,3,0.807777,6,3,1.633465,3.042589,1.354385,1.688204,0.554858,K101;K153;K185,K104;K119;K132,,0,needs_further_optimization
5,6,K101R__K104R__K153R,K101R;K104R;K153R,3,0.847840,6,3,1.569445,3.042589,1.366730,1.675859,0.550800,K101;K104;K153,K119;K132;K185,,0,needs_further_optimization
6,7,K104R__K153R__K185R,K104R;K153R;K185R,3,0.839838,6,3,1.595086,3.042589,1.412334,1.630255,0.535812,K104;K153;K185,K101;K119;K132,,0,needs_further_optimization
7,8,K119R__K132R__K153R,K119R;K132R;K153R,3,0.805952,6,3,1.557658,3.042589,1.436063,1.606525,0.528013,K119;K132;K153,K101;K104;K185,,0,needs_further_optimization
8,9,K101R__K104R__K119R,K101R;K104R;K119R,3,0.845673,6,3,1.507681,3.042589,1.445174,1.597415,0.525018,K101;K104;K119,K132;K153;K185,,0,needs_further_optimization
9,10,K101R__K104R__K185R,K101R;K104R;K185R,3,0.819597,6,3,1.484930,3.042589,1.455381,1.587208,0.521664,K101;K104;K185,K119;K132;K153,,0,needs_further_optimization
10,11,K132R__K153R__K185R,K132R;K153R;K185R,3,0.802508,6,3,1.534908,3.042589,1.457063,1.585526,0.521111,K132;K153;K185,K101;K104;K119,,0,needs_further_optimization
11,12,K104R__K153R,K104R;K153R,2,0.819667,6,4,1.070222,3.042589,1.915091,1.127498,0.370572,K104;K153,K101;K119;K132;K185,,0,needs_further_optimization
12,13,K132R__K153R,K132R;K153R,2,0.862666,6,4,1.010044,3.042589,1.960696,1.081893,0.355583,K132;K153,K101;K104;K119;K185,,0,needs_further_optimization
13,14,K101R__K132R,K101R;K132R,2,0.840352,6,4,0.899888,3.042589,2.065138,0.977451,0.321256,K101;K132,K104;K119;K153;K185,,0,needs_further_optimization
14,15,K104R__K132R,K104R;K132R,2,0.820977,6,4,0.861510,3.042589,2.106996,0.935593,0.307499,K104;K132,K101;K119;K153;K185,,0,needs_further_optimization
15,16,K119R,K119R,1,0.851707,6,5,0.547615,3.042589,2.477656,0.564933,0.185675,K119,K101;K104;K132;K153;K185,,0,needs_further_optimization

ALL RANKED

,final_rank,variant_id,mutation_spec,mutation_count,structural_preservation_score,wt_positive_count,mutant_positive_count,targeted_wt_probability_sum,wt_positive_burden,mutant_positive_burden,ubiquitination_burden_reduction,ubiquitination_burden_reduction_fraction,removed_wt_sites,remaining_wt_positive_sites,new_positive_sites,new_positive_count,R2_group
0,1,K101R__K119R__K153R__K185R,K101R;K119R;K153R;K185R,4,0.776114,6,2,2.181079,3.042589,0.847840,2.194749,0.721343,K101;K119;K153;K185,K104;K132,,0,needs_further_optimization
1,2,K101R__K132R__K153R__K185R,K101R;K132R;K153R;K185R,4,0.838986,6,2,2.034130,3.042589,0.965246,2.077343,0.682755,K101;K132;K153;K185,K104;K119,,0,needs_further_optimization
2,3,K101R__K104R__K119R__K132R,K101R;K104R;K119R;K132R,4,0.795780,6,2,1.908347,3.042589,1.061210,1.981379,0.651215,K101;K104;K119;K132,K153;K185,,0,needs_further_optimization
3,4,K101R__K119R__K153R,K101R;K119R;K153R,3,0.767060,6,3,1.656216,3.042589,1.352576,1.690013,0.555452,K101;K119;K153,K104;K132;K185,,0,needs_further_optimization
4,5,K101R__K153R__K185R,K101R;K153R;K185R,3,0.807777,6,3,1.633465,3.042589,1.354385,1.688204,0.554858,K101;K153;K185,K104;K119;K132,,0,needs_further_optimization
5,6,K101R__K104R__K153R,K101R;K104R;K153R,3,0.847840,6,3,1.569445,3.042589,1.366730,1.675859,0.550800,K101;K104;K153,K119;K132;K185,,0,needs_further_optimization
6,7,K104R__K153R__K185R,K104R;K153R;K185R,3,0.839838,6,3,1.595086,3.042589,1.412334,1.630255,0.535812,K104;K153;K185,K101;K119;K132,,0,needs_further_optimization
7,8,K119R__K132R__K153R,K119R;K132R;K153R,3,0.805952,6,3,1.557658,3.042589,1.436063,1.606525,0.528013,K119;K132;K153,K101;K104;K185,,0,needs_further_optimization
8,9,K101R__K104R__K119R,K101R;K104R;K119R,3,0.845673,6,3,1.507681,3.042589,1.445174,1.597415,0.525018,K101;K104;K119,K132;K153;K185,,0,needs_further_optimization
9,10,K101R__K104R__K185R,K101R;K104R;K185R,3,0.819597,6,3,1.484930,3.042589,1.455381,1.587208,0.521664,K101;K104;K185,K119;K132;K153,,0,needs_further_optimization
10,11,K132R__K153R__K185R,K132R;K153R;K185R,3,0.802508,6,3,1.534908,3.042589,1.457063,1.585526,0.521111,K132;K153;K185,K101;K104;K119,,0,needs_further_optimization
11,12,K104R__K153R,K104R;K153R,2,0.819667,6,4,1.070222,3.042589,1.915091,1.127498,0.370572,K104;K153,K101;K119;K132;K185,,0,needs_further_optimization
12,13,K132R__K153R,K132R;K153R,2,0.862666,6,4,1.010044,3.042589,1.960696,1.081893,0.355583,K132;K153,K101;K104;K119;K185,,0,needs_further_optimization
13,14,K101R__K132R,K101R;K132R,2,0.840352,6,4,0.899888,3.042589,2.065138,0.977451,0.321256,K101;K132,K104;K119;K153;K185,,0,needs_further_optimization
14,15,K104R__K132R,K104R;K132R,2,0.820977,6,4,0.861510,3.042589,2.106996,0.935593,0.307499,K104;K132,K101;K119;K153;K185,,0,needs_further_optimization
15,16,K119R,K119R,1,0.851707,6,5,0.547615,3.042589,2.477656,0.564933,0.185675,K119,K101;K104;K132;K153;K185,,0,needs_further_optimization

## Inspect outputs

In [13]:
print("Tables:")
for path in sorted((RUN_ROOT / "storage" / "tables").glob("*.csv")):
    print(" -", path)

print("Mutant FASTAs:", len(list((RUN_ROOT / "storage" / "mutants" / "fastas").glob("*.fasta"))))
print("WT structure directory:", RUN_ROOT / "storage" / "structures" / "wt")
print("Mutant structure directory:", RUN_ROOT / "storage" / "structures" / "mutants")

Tables:
 - /content/drive/MyDrive/therapeutic_optimization_run/storage/tables/R1_structural_screen.csv
 - /content/drive/MyDrive/therapeutic_optimization_run/storage/tables/R2_all_ranked.csv
 - /content/drive/MyDrive/therapeutic_optimization_run/storage/tables/R2_needs_further_optimization.csv
 - /content/drive/MyDrive/therapeutic_optimization_run/storage/tables/R2_optimized.csv
 - /content/drive/MyDrive/therapeutic_optimization_run/storage/tables/S1_structural_metrics.csv
 - /content/drive/MyDrive/therapeutic_optimization_run/storage/tables/S1_structurally_conserved.csv
 - /content/drive/MyDrive/therapeutic_optimization_run/storage/tables/T2_mutation_manifest.csv
 - /content/drive/MyDrive/therapeutic_optimization_run/storage/tables/UB2_mutant_ubiquitination.csv
 - /content/drive/MyDrive/therapeutic_optimization_run/storage/tables/UP1_wt_ubiquitination.csv
Mutant FASTAs: 56
WT structure directory: /content/drive/MyDrive/therapeutic_optimization_run/storage/structures/wt
Mutant structure directory: /content/drive/MyDrive/therapeutic_optimization_run/storage/structures/mutants